baseURL: 'https://www.sriniketh.dev/'
languageCode: 'en-us'
title: 'Sriniketh Ramachandran'
theme: "PaperMod"

languages:
    en:
        languageName: "English"
        weight: 1

params:
  defaultTheme: auto
  ShowReadingTime: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true

  profileMode:
    enabled: true
    title: "Hi there 👋"
    subtitle: "I'm a full stack software engineer specializing in native Android development. I'm passionate about product-led growth and solving meaningful problems at scale."

  socialIcons:
        - name: github
          url: "https://github.com/sriniketh"
        - name: linkedin
          url: "https://www.linkedin.com/in/sriniketh/"
        - name: twitter
          url: "https://twitter.com/CharPointer"
        - name: email
          url: "mailto:hello@sriniketh.dev"
